### ISSUE TITLE
is the map actually required?

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#539] opened 2018-01-11 10:39 UTC
When I include the plugin, the console sais that the map is missing. Is is really required?
if not, can you please provide a file without the link to the map so the console won't log the warning?

thank you

**Comment by kevindb** [comment] 2018-02-13 03:40
**[Instructions for Reporting a Bug](https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug)**
Would you please create an example of the error on [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) so that others can reproduce the issue you're seeing?

**Comment by kevindb** [comment] 2018-06-29 00:32
I am closing this issue due to a lack of information. If you still need help, please comment and we can reopen.

**Closed as completed by kevindb** 2018-06-29 00:32 UTC
Labels: need more info
