### ISSUE TITLE
autofill an empty form with data

### ISSUE THREAD

**Issue by stvowi** [jquery-form/form#533] opened 2017-09-28 18:34 UTC
How about it with a fillForm method such like by following plugin:

https://github.com/creative-area/jQuery-form-autofill

and a ajaxFillForm method ?

**Comment by kevindb** [comment] 2017-10-05 15:12
Duplicate of #528
------
It seems like jQuery-form-autofill would do what you're asking for.

**Closed as completed by kevindb** 2017-10-05 15:12 UTC
Labels: duplicate, wontfix, feature
